### ISSUE TITLE
Failed to Import Pack

### ISSUE THREAD

**Issue by applejvcks** [gd-codes/mc-pixelart-maker#10]
When I create the pack and try to open it, it gives me this error:
![image](https://github.com/gd-codes/mc-pixelart-maker/assets/134894093/4b299d2c-972f-46e8-a96d-305046894443)

Here's the output log:
![image](https://github.com/gd-codes/mc-pixelart-maker/assets/134894093/5e382675-945d-4e19-aca6-fc35d7ee34aa)
![image](https://github.com/gd-codes/mc-pixelart-maker/assets/134894093/801ae9f2-f4d7-407a-b06c-5bd21ebeeb07)

Not sure what's causing this, I've been using this for a while and had no problems like this.
(EDIT: I am on v.1.19.83)

**Comment by gd-codes** [comment]
Thanks for letting me know... This is a strange error and I haven't encountered it before, so unfortunately I'm not too sure what to do either.

Does it occur repeatedly? Try clearing your browser's cache (at least for this 1 site) and reload the page before creating the addon again.
If the manifest file was missing as your screenshot shows, then the Javascript of the website that writes it didn't load properly that one time for some reason (network connection maybe?). Hopefully this'll be okay the next time.

Otherwise, could you share the logs that appear in the Browser console? (In Chrome, Edge, etc right click anywhere on the webpage and perform "Inspect". Then find the "Console" tab there. Open that first, then refresh the page and start processing your pictures. Any error messages will appear there as you keep changing settings and generate and finally download the pack)

**Comment by applejvcks** [comment]
Turns out this was an issue on my end. It had something to do with moving Minecraft from my C drive to my D drive, which encryted my program files or something? Either way, I uninstalled and reinstalled and everything is working fine!

Thank you for the help and sorry for the delay!
