### ISSUE TITLE
Map Art Maker for Java Edition

### ISSUE THREAD

**Issue by mrgitrog** [gd-codes/mc-pixelart-maker#2]
Hey! Is it at all possible to use this for Java Edition of Minecraft, or is it possible to be edited for Java Edition? Sorry for making a GitHub issue out of this, I didn't see any other forms of contact on the website. Thanks!

**Comment by gd-codes** [comment]
Hi !

No problem with opening an issue here! The app currently works only for Bedrock edition. Actually, one of the main reasons that motivated me to publish it was that I didn't find any map art tools for Bedrock, that also worked in a vanilla sort of way without modifying the world dat files etc... 

I suppose it's possible to modify it for Java - there'll be 2 major parts that need to be changed - the Colour palette (the table in the webpage, & the RGB values which are currently hardcoded into image processing script), and the addon format (the mcfunction files can stay the same iirc, but the rest of the java datapack structure is different).

Unfortunately, this'll take a bit of effort to do, and I wasn't planning to make any changes soon. I suppose that you could use some of the other map art generator tools available online like [MapArtCraft](https://rebane2001.com/mapartcraft/) ? (It seems to be quite popular, though I haven't tried it myself since I don't play on Java Edition much).
 However, making the colour palette easier to edit is something I want to do when I next get a chance (I'll probably have to do that anyway when 1.19 arrives, since there are new blocks etc & the palette will most likely change). Maybe at some point in the future I'll add a Java edition version of the site !
