### ISSUE TITLE
Showing the /execute command

### ISSUE THREAD

**Issue by Kitsune865** [gd-codes/mc-pixelart-maker#3]
Would it be possible to show the command that actually takes place in game on the website? As it would allow these to be built on realms and such. No worries if you can't, but it would be a quality of life improvement to copy and paste a command into a command block and bam, same result.

**Comment by shadows-coding** [comment]
(I am not the creator of this website but I do have some experience with Minecraft bedrock commands)

Hello I don’t think there’s a way to place down so many blocks in _one command_ without making a function (that contains many different commands) and then doing /function NameOfFunction

I’m pretty sure that’s what this website is doing

PS
A single command might be possible on Java addition.
Because I’ve seen some people make command block machines
Out of one command block that places down more command blocks
It unfortunately requires NBT data which is not available on the bedrock addition…

**Comment by gd-codes** [comment]
Hi !
Yes, it would be possible to do that. But I'd like to clarify something - by "_the command that actually takes place in game_", do you mean only the ones the player has to run (which are just 2-32 `/function` commands), or every single command that is actually executed to build the structure? 
Functions are just files containing other minecraft commands, which are run en masse, and they just make things convenient when the number of commands actually executed is **huge** (like here - 16,384 for a single map). These are all unique`/setblock` commands for each individual block - there's no way to shorten them, like shadows-coding mentioned.

So even if the website did display the commands, it might be impractical to run by copy pasting them manually. This is in case you're thinking of running them directly as an alternative to having to apply the behaviour pack / addon to a realm.

I described this on [the site's info page too](https://gd-codes.github.io/mc-pixelart-maker/manual.html). There's also a sample pack at the end of that page which you can open and look into (with the function files) to get an idea of what is actually executed.

**Comment by Kitsune865** [comment]
Fair enough, it was just to see if there was an easily executable method of using the art on a multiplayer server outside of the add-on

**Comment by shadows-coding** [comment]
Lol you could possibly make A macro generator that types out all the commands for you…
it would only be a little bit more practical than typing it out yourself and it would take a long time.
But that would definitely be a very funny creation!
