### ISSUE TITLE
Suggestion: To add materials list for whole map art

### ISSUE THREAD

**Issue by Lonely13X14** [gd-codes/mc-pixelart-maker#6]
Pleasant day. I would like to ask if it would be possible to make a materials list type which displays all the materials needed cumulative of all the zones. I know that materials list for each individual zone is provided next to the survival placement guide, but since I make large map arts, it gets hard to go to each of them and add them all manually. It would be a quality of life change if it could be implemented, Thank you for reading this and apologies that I opened this as a issue, I was not sure of where else to contact.

**Comment by gd-codes** [comment]
Sure, that's definitely possible

I'll try to work on it along with the fix for the other currently open issue. (Though unfortunately I haven't been getting much free time to work on these updates lately, so it may be a while before I publish it....)

Thank you for the suggestion, and feel free to use this issues page to communicate any ideas!

**Comment by gd-codes** [comment]
I've implemented this now

**Comment by Lonely13X14** [comment]
Thank you very much for your efforts.
