### ISSUE TITLE
Black pixels are turning gray

### ISSUE THREAD

**Issue by MaritimeOcean41** [gd-codes/mc-pixelart-maker#7]
I've been using the site for a while, but today when I went to place an image the black pixels were gray, not in the image! But yes in the "Survival Guide" and there's no black block [black is not blocked! But when I block the gray it turns black where it should | And before with this same image the gray part was black]

It's like this in the preview:
![image](https://user-images.githubusercontent.com/76133361/192319117-140321b5-eb0e-4430-83f1-699a96cb4623.png)

But so in the "Survival Guide"
![image](https://user-images.githubusercontent.com/76133361/192319403-564963ea-3c56-4fd8-a1b7-d798eaee421e.png)

**Comment by gd-codes** [comment]
I guess that this is because the colour in the original image wasn't _exactly_ black. The code automatically picks the closest colour (according to a mathematical formula) from the palette materials that you allow.

Was the last time you used the site more than 5 weeks ago ? I added fixes for some bugs at that time, one of which was to do with incorrect colours, so the palette changed after that website update. 
This new version will actually be more accurate in the sense that what you see in Minecraft now will better match the preview on the website; compared to some differences that might have been visible before the update.
Also, sometimes different devices/browsers will show slightly different results, mainly in images with Dithering or resizing, since some image operations like the resize are done by the browser's math and not my code.

If you'd like to use only black and not grey, I suppose that some things you could try are
- Editing the original image to make the pixels blacker (RGB = 0,0,0 or close to that) before uploading it
- Or else unselecting Gray Dye and similar shades in the palette before processing the image, so that the new closest colour is only Black Dye and/or Sculk. Although this will force the code to avoid Grey Dye across the entire image.

**Comment by MaritimeOcean41** [comment]
Thanks! This worked, I think it must be because minecraft added more map colors in 1.19, and before the color #222222 was identified as black
