### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by Hemuli5407** [gd-codes/mc-pixelart-maker#8]
First of all, a great website! Makes bedrock map artists jobs so much easier. But for the suggestion, there's already a software that lets you convert any structure block files into texture pack, which you can enable, place armour stand and it lets you see where to place blocks for a build, or map art. 
( https://ravinmaddhatter.com/2022/09/14/structura-1-5/ , https://github.com/RavinMaddHatter/Structura/releases/tag/v1.5Beta )

 but the process of taking structure block copies of a map art and then running them through the app is impossible on mobile, and slightly confusing on pc to people that have never used the app before. So would it be possible to somehow work with Ravinmaddhatter, and implement that as a feature to your website? It would make server/survival map art making so much simplier. 

Picture below what it looks like. Structure blocks have some limitations though. for a 2d 128x128 map art you need to make               2x 64x42 and 64x43 4 times, even then the right bottom corner sometimes gets unrendered. for a 3d map i think you'd need at least 8 texture packs.  

![Minecraft 27_09_2022 21 06 09](https://user-images.githubusercontent.com/107268240/192603150-adf61bba-194e-4588-ab3d-503d787ce313.png)

**Comment by gd-codes** [comment]
Thanks for the suggestion !
It sounds like a great idea - and will make the building process without commands much easier. 

I'm assuming that if there was to be an extension to either app that added this functionality, it would be simpler to remove the structure block format as an intermediary, and communicate which blocks to highlight where in another way, since in both apps the purpose of some code will only be to decipher this from other formats (an image in my case, or the mcstructure file in Structura), and that gets rid of these restrictions and more processing/conversion etc...

Though, as a side note, as I wrote in a few places around the website, I haven't been getting too much free time lately to devote to this, which started just as a one-time hobby project 😅. So it may be a while before I consider starting work on something like this. 
I'll leave this post open for now so that anyone else who comes across the site and has some know-how about the minecraft structure file and JSON geometry file definitions & format etc, can comment if they're interested. Pull requests and contributions are welcome!
